#!/usr/bin/env python3
"""Bundle the experiment editor's source modules into depibeans/ui/dist/app.js.

    python3 tools/build_ui.py            rebuild the generated region of app.js
    python3 tools/build_ui.py --check    exit 1 if app.js is not what the sources produce

The editor is written as small ES modules in depibeans/ui/src/editor (unit-testable
with `node --test tests/js`). The portal serves one plain script, so the modules are
concatenated, in dependency order, inside a single private function scope. There is
no third-party bundler: the output depends only on the source files, byte for byte.

Rules the sources must follow, enforced here:
  - imports are single-line `import { a, b } from './x.js';` of sibling modules;
  - exports are `export const|function|class name`;
  - a top-level name is declared in exactly one module (they share one scope).
"""
from __future__ import annotations
import argparse, hashlib, re, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / 'depibeans/ui/src/editor'
TARGET = ROOT / 'depibeans/ui/dist/app.js'
ENTRY = 'editor.js'
PUBLIC = {'install': 'installEditor'}
BEGIN = '// <editor-bundle> GENERATED by tools/build_ui.py from depibeans/ui/src/editor. Edit the sources, then rebuild.'
END = '// </editor-bundle>'

IMPORT = re.compile(r"^import \{([^}]*)\} from '\./([\w-]+\.js)';\s*$")
DECLARATION = re.compile(r'^(?:export )?(?:const|let|function|class)\s+([A-Za-z_$][\w$]*)')


def load(name: str):
    text = (SOURCE / name).read_text(encoding='utf-8')
    imports, body = [], []
    for number, line in enumerate(text.splitlines(), 1):
        if line.startswith('import '):
            match = IMPORT.match(line)
            if not match:
                raise SystemExit(f'{name}:{number}: only single-line sibling imports are supported: {line}')
            imports.append((match.group(2), [part.strip() for part in match.group(1).split(',') if part.strip()]))
            continue
        if line.startswith('export ') and not DECLARATION.match(line):
            raise SystemExit(f'{name}:{number}: unsupported export form: {line}')
        body.append(line[len('export '):] if line.startswith('export ') else line)
    return text, imports, body


def ordered_modules():
    seen, order, loaded = set(), [], {}

    def visit(name, trail):
        if name in trail:
            raise SystemExit('Import cycle: ' + ' -> '.join(trail + [name]))
        if name in seen:
            return
        if not (SOURCE / name).is_file():
            raise SystemExit(f'Missing module {name}')
        loaded[name] = load(name)
        for dependency, _ in sorted(loaded[name][1]):
            visit(dependency, trail + [name])
        seen.add(name)
        order.append(name)

    visit(ENTRY, [])
    return order, loaded


def bundle() -> str:
    order, loaded = ordered_modules()
    unused = sorted(path.name for path in SOURCE.glob('*.js') if path.name not in loaded)
    if unused:
        raise SystemExit('Modules not reachable from ' + ENTRY + ': ' + ', '.join(unused))
    owners, exported = {}, {}
    for name in order:
        text, _, body = loaded[name]
        exported[name] = set()
        for original, line in zip([l for l in text.splitlines() if not l.startswith('import ')], body):
            match = DECLARATION.match(original)
            if not match or original[:1].isspace():
                continue
            identifier = match.group(1)
            if identifier in owners:
                raise SystemExit(f'"{identifier}" is declared at top level in both {owners[identifier]} and {name}')
            owners[identifier] = name
            if original.startswith('export '):
                exported[name].add(identifier)
    for name in order:
        for dependency, names in loaded[name][1]:
            missing = [identifier for identifier in names if identifier not in exported[dependency]]
            if missing:
                raise SystemExit(f'{name} imports {", ".join(missing)} which {dependency} does not export')
    digest = hashlib.sha256()
    parts = []
    for name in order:
        text, _, body = loaded[name]
        digest.update(name.encode() + b'\0' + text.encode('utf-8') + b'\0')
        while body and not body[-1].strip():
            body.pop()
        parts.append(f'// ---- {name} ' + '-' * max(4, 70 - len(name)) + '\n' + '\n'.join(body).strip('\n'))
    public = ', '.join(f'{key}: {value}' for key, value in PUBLIC.items())
    return '\n'.join([
        BEGIN,
        f'// sources sha256 {digest.hexdigest()}',
        'const DepiEditor = (() => {',
        '\n\n'.join(parts),
        f'return {{ {public} }};',
        '})();',
        END,
    ])


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--check', action='store_true', help='verify app.js is up to date; change nothing')
    arguments = parser.parse_args()
    current = TARGET.read_text(encoding='utf-8')
    if current.count(BEGIN) != 1 or current.count(END) != 1:
        raise SystemExit(f'{TARGET} must contain exactly one editor-bundle region')
    start, stop = current.index(BEGIN), current.index(END) + len(END)
    rebuilt = current[:start] + bundle() + current[stop:]
    if rebuilt == current:
        print('app.js is up to date')
        return 0
    if arguments.check:
        print('app.js is stale: run python3 tools/build_ui.py', file=sys.stderr)
        return 1
    TARGET.write_text(rebuilt, encoding='utf-8')
    print('rebuilt editor bundle in', TARGET.relative_to(ROOT))
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
